name: family_note
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  dio: ^5.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  go_router: ^13.1.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ">=4.0.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
